
name: Deploy Bunny Scripting Script

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install
        run: "cd bgg-bunny && npm install"

      - name: Build
        run: "cd bgg-bunny && npx esbuild board-games-api.ts --bundle --format=esm --outfile=dist/index.js --platform=browser --target=es2022"

      - name: Publish the script to Bunny
        uses: "BunnyWay/actions/deploy-script@main"
        with:
          script_id: 61994
          file: "bgg-bunny/dist/index.js"
