
name: Deploy Bunny Scripting Script

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install
        run: "cd bgg-bunny && npm install"

      - name: Build Board Games API
        run: "cd bgg-bunny && npx esbuild board-games-api.ts --bundle --format=esm --outfile=dist/board-games.js --platform=browser --target=es2022 --external:@bunny.net/edgescript-sdk"

      - name: Build Bookings API
        run: "cd bgg-bunny && npx esbuild bookings-edge-script.ts --bundle --format=esm --outfile=dist/bookings.js --platform=browser --target=es2022 --external:@bunny.net/edgescript-sdk"

      - name: Build Emails API
        run: "cd bgg-bunny && npx esbuild emails-edge-script.ts --bundle --format=esm --outfile=dist/emails.js --platform=browser --target=es2022 --external:@bunny.net/edgescript-sdk"

      - name: Publish Board Games Script to Bunny
        uses: "BunnyWay/actions/deploy-script@main"
        with:
          script_id: 61994
          file: "bgg-bunny/dist/board-games.js"

      - name: Publish Bookings Script to Bunny
        uses: "BunnyWay/actions/deploy-script@main"
        with:
          script_id: 63643
          file: "bgg-bunny/dist/bookings.js"

      - name: Publish Emails Script to Bunny
        uses: "BunnyWay/actions/deploy-script@main"
        with:
          script_id: 63560
          file: "bgg-bunny/dist/emails.js"

